name: deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'

      - run: npm i # TODO: --production
      - run: npm run build

      - uses: easingthemes/ssh-deploy@v2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_PORT: ${{ secrets.PORT }}
          REMOTE_USER: ${{ secrets.USER }}
          TARGET: ${{ secrets.DIR }}
          SOURCE: 'dist ecosystem.config.js'

      - uses: appleboy/ssh-action@v0.1.3 #TODO: remove?
        with:
          key: ${{ secrets.KEY }}
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          script_stop: true
          script: |
            cd ${{ secrets.DIR }}
            pm2 start
