name: Deploy
on:
  push:
    branches:
      - master

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Setup Yarn
        run: npm i -g yarn

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install deps
        run: yarn

      - name: Build
        run: yarn build

      - name: Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1
        with:
          username: 'root'
          server: 'ceigh.com'
          ssh_private_key: ${{ secrets.PRIVATE_KEY }}
          local_path: './.nuxt/*'
          remote_path: '/var/www/ceigh.com/.nuxt'
          args: '-o ConnectTimeout=5'

      - name: Reload
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: pm2 reload ceigh.com
          host: ceigh.com
          username: root
          privateKey: ${{ secrets.PRIVATE_KEY }}

      - name: Update repository
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd /var/www/ceigh.com && git pull
          host: ceigh.com
          username: root
          privateKey: ${{ secrets.PRIVATE_KEY }}
