name: Deploy
on:
  push:
    branches:
      - master

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Yarn
        run: npm i -g yarn

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Copy
        uses: garygrossgarten/github-action-scp@v0.6.0
        with:
          local: .nuxt
          remote: ${{ secrets.DIR }}/.nuxt
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          privateKey: ${{ secrets.PRIVATE_KEY }}

      - name: Reload
        uses: garygrossgarten/github-action-ssh@v0.5.0
        with:
          command: pm2 reload ${{ secrets.HOST }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
