name: deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: '15'

      - run: npm --global install yarn
      - run: yarn --silent
      - run: yarn build

      - uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          ssh_private_key: ${{ secrets.KEY }}
          server: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          local_path: '.nuxt'
          remote_path: ${{ secrets.DIR }}


      - uses: appleboy/ssh-action@v0.1.3
        with:
          key: ${{ secrets.KEY }}
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          script_stop: true
          script: |
            cd ${{ secrets.DIR }}
            git pull
            yarn --silent
            pm2 --mini-list start
